### ISSUE TITLE
SIGSEGV converting file

### ISSUE THREAD

**Issue by ronaaron** [ligurio/gedcom2sql#1]
Just found your tool.  Installed go on my MacBook, did 'go build gedcom2sql' and then:

~/src/gedcom-tools$ ./gedcom2sql -file aaron.ged
Found persons: 694
Found families: 232
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40fbbce]

goroutine 1 [running]:
main.main()
	/Users/ron/src/gedcom-tools/gedcom2sql.go:180 +0x101e
~/src/gedcom-tools$

**Comment by ronaaron** [comment]
running -verbose, I see that it's dying on a family which doesn't have a husband

**Comment by ronaaron** [comment]
closed by accident...

**Comment by ligurio** [comment]
@ronaaron, thanks for the report! It is actually an issue in a gedcom parsing package used in gedcom2sql. Issue has been already submitted to the author of the package - https://github.com/iand/gedcom/issues/4
